usuario_login:
    path: /
    defaults: { _controller: UsuarioBundle:Usuario:login }
    
usuario_validar:
    path: /Valida
    defaults: { _controller: UsuarioBundle:Usuario:validar }
    
menu_list:
    path: /Usuario/Menu/list
    defaults: { _controller: UsuarioBundle:Menu:list }

usuario_add:
    path: /Usuario/add
    defaults: { _controller: UsuarioBundle:Usuario:add }

usuario_list:
    path: /Usuario/list
    defaults: { _controller: UsuarioBundle:Usuario:list }
    
usuario_edit:
    path: /Usuario/edit/{id}
    defaults: { _controller: UsuarioBundle:Usuario:edit }
    
usuario_delete:
    path: /Usuario/delete/{id}
    defaults: { _controller: UsuarioBundle:Usuario:delete }