UsuarioBundle\Entity\Usuario:
    type: entity
    table: null
    repositoryClass: UsuarioBundle\Repository\UsuarioRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        rolId:
            type: integer
            column: rol_id
        rut:
            type: string
            length: '12'
        nombres:
            type: string
            length: '50'
        apellidoP:
            type: string
            length: '50'
        apellidoM:
            type: string
            length: '50'
        username:
            type: string
            length: '50'
        password:
            type: string
            length: '50'
        email:
            type: string
            length: '50'
    lifecycleCallbacks: {  }
