MenuBundle\Entity\Menu:
    type: entity
    table: null
    repositoryClass: MenuBundle\Repository\MenuRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nombre:
            type: string
            length: 255
        ruta:
            type: string
            length: 255
        listar:
            type: boolean
        agregar:
            type: boolean
        editar:
            type: boolean
        eliminar:
            type: boolean
    lifecycleCallbacks: {  }
