ProveedorBundle\Entity\Proveedor:
    type: entity
    table: null
    repositoryClass: ProveedorBundle\Repository\ProveedorRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nombres:
            type: string
            length: '60'
        apellidoP:
            type: string
            length: '60'
        apellidoM:
            type: string
            length: '60'
        rut:
            type: string
            length: '12'
        razonSocial:
            type: string
            length: '60'
        email:
            type: string
            length: '50'
        fono:
            type: string
            length: '20'
    lifecycleCallbacks: {  }
