<?php

namespace MenuRolBundle\Repository;

/**
 * Menu_rolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Menu_rolRepository extends \Doctrine\ORM\EntityRepository
{
}
